import assert from 'node:assert/strict';
import {readFile, mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
import {mergeCatalog,resolveMapping} from '../src/core.mjs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});
const context=await browser.newContext({viewport:{width:1280,height:900},acceptDownloads:true});
const network=[];
await context.route(/^https?:\/\//,route=>{network.push(route.request().url());return route.abort();});
const page=await context.newPage(),errors=[];
page.on('pageerror',error=>errors.push(error.message));
const url=new URL('../index.html',import.meta.url).href;
const catalog=mergeCatalog(JSON.parse(await readFile(new URL('../data/pricing.json',import.meta.url),'utf8')),JSON.parse(await readFile(new URL('../data/catalog-snapshot.json',import.meta.url),'utf8')));
const qwenRates=resolveMapping('qwen3.6:35B',catalog).rates;
const qwenCost=new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(qwenRates.input+qwenRates.output/10);
const row=(model='qwen3.6:35B',provider='ollama',input=1000000,output=100000)=>({model,provider,count:10,totals:{input,output,totalTokens:input+output}});
const data=rows=>({startDate:'2026-09-01',endDate:'2026-09-30',aggregates:{byModel:rows,daily:[{date:'2026-09-01'},{date:'2026-09-30'}]}});
async function importData(value){await page.locator('#jsonInput').fill(JSON.stringify(value));await page.getByRole('button',{name:'Analyze usage',exact:true}).click();}
async function summary(){return page.locator('#summaryCards').innerText();}
let checks=0;
const check=(condition,message)=>{assert.ok(condition,message);checks++;};
try{
  await page.goto(url);
  check(await page.locator('#results').isHidden(),'starts with an honest empty state');
  await page.getByRole('button',{name:'Load synthetic demo'}).click();
  check((await summary()).includes('4,900,000'),'synthetic demo counts all tokens');
  check((await summary()).includes('Unavailable'),'unpriced demo model suppresses savings');
  check((await page.locator('#importStatus').innerText()).includes('Synthetic'),'demo is labeled');
  await importData(data([row()]));
  check((await summary()).includes('30 calendar days'),'observation range includes idle days');
  check((await page.locator('#modelPicker-0').inputValue())==='or-qwen36-35b','requested model maps directly');
  check((await summary()).includes(qwenCost),'Qwen 3.6 uses bundled current catalog rates');
  await page.locator('#hwScenario').selectOption('buy');await page.locator('#hwPrice').fill('1200');
  check((await summary()).includes('$1,200.00'),'hardware edits update immediately');
  await page.locator('#hwAccounting').selectOption('depreciation');await page.locator('#hwMonths').fill('12');await page.locator('#projectionRange').selectOption('1095');
  check((await page.locator('#projectionPanel').innerText()).includes('$1,200.00'),'depreciation is capped');
  await page.locator('#elecEnabled').check();await page.locator('#hwRate').fill('0');
  check((await summary()).includes('$0.00 electricity'),'zero rate respected');
  await page.locator('#hwHours').fill('25');
  check(await page.locator('#settingsError').isVisible(),'bad settings have a visible error');check(await page.locator('#export').isDisabled(),'invalid settings cannot export stale totals');await page.locator('#hwHours').fill('8');
  const attack='<img src="data:image/png,invalid" onerror="document.body.dataset.pwned=1">';
  await importData(data([row(attack,attack)]));
  check(await page.locator('#usageTable tbody img').count()===0,'imported markup is text');check(await page.locator('body').getAttribute('data-pwned')===null,'import cannot execute JavaScript');check((await summary()).includes('Price unknown'),'unknown model does not become free');
  await page.getByRole('button',{name:'Set custom rates'}).click();await page.locator('#customName').fill(attack);await page.locator('#customProvider').fill(attack);await page.locator('#customInput').fill('0');await page.locator('#customOutput').fill('0');await page.getByRole('button',{name:'Save pricing',exact:true}).click();
  check((await summary()).includes('$0.00'),'custom zero rates are accepted');check(await page.locator('#usageTable tbody img').count()===0,'custom markup is text');
  await importData(data([row('toString'),row('qwen3.6:35B','ollama'),row('qwen3.6:35B','cloud')]));
  check(await page.locator('#usageTable tbody tr').count()===3,'provider identity preserved and inherited keys safe');
  const before=await summary();await page.getByLabel('Role for qwen3.6:35B from ollama',{exact:true}).selectOption('Primary');check((await summary()).includes('3,300,000')&&before.includes('3,300,000'),'assigning a role does not filter usage');
  await page.locator('#roleFilter').selectOption('Primary');check((await summary()).includes('1,100,000'),'explicit role filter works');
  await page.locator('#alternativePicker').selectOption('openai-luna');await page.getByRole('button',{name:'Add comparison',exact:true}).click();
  check((await page.locator('#alternativeTable').innerText()).includes('$0.32 – $0.58'),'unknown per-request tiers have a full cost range');
  check((await page.locator('#alternativeTable').innerText()).includes('1,100,000 of 1,100,000 tokens priced'),'context uncertainty does not reduce coverage');
  const projectionToggle=page.getByRole('checkbox',{name:/Show .* on the projection/});check(await projectionToggle.count()===1,'each comparison has an opt-in projection checkbox');
  await projectionToggle.check();check((await page.locator('.projection-legend').innerText()).includes('Luna'),'selected comparison is identified in the projection legend');
  check(await page.locator('#projectionPanel svg polyline').count()>=3,'selected comparison adds its own projection line');
  await page.locator('#contextMode').selectOption('limit');check(await page.locator('#contextLimit').inputValue()==='270000','user context limit is prefilled exactly');
  check((await page.locator('#alternativeTable').innerText()).includes('$0.32')&&!(await page.locator('#alternativeTable').innerText()).includes('$0.58'),'270000 resolves the standard scenario');
  await page.locator('#contextLimit').fill('276480');check((await page.locator('#alternativeTable').innerText()).includes('$0.32 – $0.58'),'higher limit retains uncertainty rather than forcing high rates');
  await page.locator('#contextLimit').fill('0');check(await page.locator('#export').isDisabled()&&await page.locator('#settingsError').isVisible(),'invalid context limit blocks stale export');
  await page.locator('#contextLimit').fill('270000');
  const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;const report=JSON.parse(await readFile(await download.path(),'utf8'));
  check(report.models.length===3&&report.summary.conclusionAvailable,'report includes current scope and assumptions');check(!('sessions' in report),'report contains no raw session metadata');
  check(report.schemaVersion===2&&report.pricingAssumptions.contextLimit===270000&&report.pricingAssumptions.contextMode==='limit','report preserves declared context');
  check(report.alternatives[0].showOnProjection&&report.projection.alternatives.length===1,'report preserves selected projection comparisons');
  await page.locator('#contextMode').selectOption('range');await page.locator('#modelSearch-1').fill('Astra');await page.locator('#modelPicker-1').selectOption('openai-astra');
  await page.locator('#hwAccounting').selectOption('purchase');await page.locator('#hwPrice').fill('20');
  check((await summary()).includes('$15.00 – $27.50')&&(await summary()).includes('Depends on context'),'full range and uncertain savings appear together');
  check(await page.locator('#projectionPanel svg polygon').count()===1,'projection shows an uncertainty band');
  const rangeDownloadPromise=page.waitForEvent('download');await page.locator('#export').click();const rangeDownload=await rangeDownloadPromise;const rangeReport=JSON.parse(await readFile(await rangeDownload.path(),'utf8'));
  check(rangeReport.summary.cost===null&&rangeReport.summary.lowCost===15&&rangeReport.summary.highCost===27.5&&rangeReport.summary.coverage===1,'range export preserves full coverage without inventing a scalar');
  check(rangeReport.summary.winnerDetermined===false&&rangeReport.summary.comparison.winner==='uncertain'&&rangeReport.projection.hostedRange.high>rangeReport.projection.hostedRange.low,'uncertainty survives savings and projection export');
  await page.locator('#contextMode').selectOption('long');check((await summary()).includes('$27.50')&&!(await summary()).includes('Depends on context'),'explicit high scenario resolves the comparison');
  await page.locator('#contextMode').selectOption('standard');check((await summary()).includes('$15.00')&&!(await summary()).includes('Depends on context'),'explicit standard scenario resolves the comparison');
  await page.locator('#modelSearch-1').fill('qwen3.6');await page.locator('#modelPicker-1').selectOption('or-qwen36-35b');await page.locator('#contextMode').selectOption('range');
  const sensitive=data([row()]);sensitive.secret='SYNTHETIC_SENSITIVE_VALUE';sensitive.sessions=[{label:'SYNTHETIC_PRIVATE_SESSION',origin:{from:'SYNTHETIC_PRIVATE_CONTACT'}}];await page.locator('#roleFilter').selectOption('All');
  await page.locator('#fileInput').setInputFiles({name:'usage.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(sensitive))});await page.waitForFunction(()=>document.getElementById('usageTable').querySelectorAll('tbody tr').length===1);
  const privateDownloadPromise=page.waitForEvent('download');await page.locator('#export').click();const privateDownload=await privateDownloadPromise;const privateText=await readFile(await privateDownload.path(),'utf8');check(!privateText.includes('SYNTHETIC_'),'file imports discard irrelevant metadata from export');
  await mkdir(new URL('../test-results/',import.meta.url),{recursive:true});await page.screenshot({path:fileURLToPath(new URL('../test-results/desktop.png',import.meta.url)),fullPage:true});
  await page.setViewportSize({width:390,height:844});check(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),'mobile has no page-level horizontal overflow');await page.screenshot({path:fileURLToPath(new URL('../test-results/mobile.png',import.meta.url)),fullPage:true});
  await page.locator('#jsonInput').fill('null');await page.locator('#analyze').click();check(await page.locator('#error').isVisible()&&await page.locator('#results').isHidden(),'invalid import hides stale results');
  await page.locator('#reset').click();check(await page.locator('#jsonInput').inputValue()===''&&await page.locator('#results').isHidden(),'reset clears imported data');
  check(await page.locator('#contextMode').inputValue()==='range'&&await page.locator('#contextLimit').inputValue()==='270000','reset restores range and exact context preset');
  await importData(data([row('qwen2.5:3b-instruct')]));
  check(await page.locator('#modelPicker-0').inputValue()==='','historical substitute is not automatically accepted');
  check((await page.locator('#projectionPanel').innerText()).includes('qwen2.5:3b-instruct'),'projection names the specific unpriced model');
  const suggested=page.locator('.suggestions button').first();check((await suggested.innerText()).includes('Use alternative:')&&(await suggested.innerText()).includes('per 1M'),'suggestion includes rates and alternative label');
  await suggested.click();check(!(await summary()).includes('Price unknown'),'accepting the priced alternative populates its cost');
  await page.getByRole('button',{name:'Set custom rates',exact:true}).click();check(await page.locator('#customInput').inputValue()!==''&&await page.locator('#customOutput').inputValue()!=='','selected catalog rates populate the custom dialog');await page.locator('#cancelPricing').click();
  check((await page.locator('#catalogAuditSummary').innerText()).includes('three public sources'),'audit is bundled with the page');
  check(network.length===0,'app makes zero network requests');assert.deepEqual(errors,[],'no runtime errors');console.log(`${checks} browser checks passed; file://, CSP, imports, XSS, custom pricing, filtering, hardware, exports and mobile verified.`);
}finally{await browser.close();}
